const options = [
  "ADDNICE",
  "ADIDAS",
  "ALPINE SKATE",
  "ARGOLF",
  "ASICS",
  "ATHIX",
  "ATOMIK",
  "BABOLAT",
  "BEST SOX",
  "BODY",
  "CAPSLAB",
  "CARTAGO",
  "CHAMPION",
  "CONVERSE",
  "CROCS",
  "DAK",
  "DIADORA",
  "DRB",
  "FILA",
  "FLASH",
  "FOOTY",
  "HAVAIANAS",
  "HEAD",
  "HIFEL",
  "IPANEMA",
  "JACK LEE",
  "JOHN FOOS",
  "KAPPA",
  "LA DOLFINA",
  "LA GEAR",
  "LACOSTE",
  "LECOQ",
  "MARISA",
  "MITRE",
  "MONTAGNE",
  "NEW BALANCE",
  "NIKE",
  "OLYMPIKUS",
  "OPORTUNIDADES",
  "PENALTY",
  "PONY",
  "PROCER",
  "PROFIT",
  "PUMA",
  "QUIKSILVER",
  "REEBOK",
  "REEF",
  "REUSCH",
  "REVES",
  "SNAUWAERT",
  "SPORT COMPLEMENT",
  "SPORT SERVICES",
  "TOPPER",
  "UMBRO",
  "UNDER ARMOUR",
  "VANS",
  "WILSON",
];

const brandOptions = options.map((brand) => ({
  value: brand,
  label: brand,
}));

const value = [
  { value: "10%", label: "10 %" },
  { value: "20%", label: "20 %" },
  { value: "30%", label: "30 %" },
  { value: "40%", label: "40 %" },
  { value: "50%", label: "50 %" },
];

export { brandOptions, value };
